#!/bin/bash
echo "=== OpenClaw V3 Daily Report — $(date '+%Y-%m-%d %H:%M') ==="
echo ""
echo "--- Infrastructure Modules ---"
echo "Vault: $(curl -sf http://127.0.0.1:8200/v1/sys/health | python3 -c "import json,sys; print('HEALTHY' if json.load(sys.stdin).get('initialized') else 'UNHEALTHY')" 2>/dev/null || echo "NOT RUNNING")"
echo ""
echo "--- Agent Room v2 ---"
cd ~/.openclaw/modules/agent-room-v2 2>/dev/null && bash monitoring/queue-metrics.sh 2>/dev/null || echo "Queue metrics unavailable"
echo ""
echo "--- Token Budgets ---"
cd ~/.openclaw/modules/token-budgets 2>/dev/null && bash monitoring/budget-status.sh 2>/dev/null || echo "Budget status unavailable"
echo ""
echo "--- Smart Router v2 ---"
cd ~/.openclaw/modules/smart-router-v2 2>/dev/null && bash monitoring/cost-dashboard.sh 2>/dev/null || echo "Cost dashboard unavailable"
echo ""
echo "--- Degraded Mode ---"
echo "Status: $(cat ~/.openclaw/modules/degraded-mode/data/current-state.json 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin).get('mode','unknown'))" 2>/dev/null || echo "normal (no incidents)")"
echo ""
echo "=== Report Complete ==="
